repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.24.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        language_version: python3
        stages: [commit]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        stages: [commit]
  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        name: pylint
        language: python
        entry: pylint
        types:
          - python
        stages: [commit]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.371
    hooks:
      - id: pyright
        stages: [commit]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: pytest -v
        always_run: false
        pass_filenames: false
        stages: [commit]
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        language: system
        entry: bash -c ".venv/bin/pip3 freeze > requirements.txt; git add requirements.txt"
        always_run: true
        pass_filenames: false
        stages: [commit]
