POST http://localhost:8080/books
Content-Type: application/json

{
    "title": "1984",
    "user_id": 1
}

###
GET http://localhost:8080/books
Content-Type: application/json

###
GET http://localhost:8080/books/
Content-Type: application/json

###
GET http://localhost:8080/books/user/
Content-Type: application/json

###
PATCH http://localhost:8080/books/
Content-Type: application/json

{
    "title": "Admiravel Mundo Novo"
}

###
PATCH http://localhost:8080/books/toggle-status/
Content-Type: application/json

{
}

###
DELETE http://localhost:8080/books/
Content-Type: application/json
