POST http://localhost:8080/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "age": 30
}
###
GET http://localhost:8080/users
Content-Type: application/json

###
PATCH http://localhost:8080/users/
Content-Type: application/json

{
    "name": "Mary Doe",
    "email": "mary.doe@example.com",
    "age": 30
}

###
DELETE http://localhost:8080/users/
Content-Type: application/json
